version: '3'
services:
  db:
    container_name: bingo-db
    image: postgres:alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=bingo
      - POSTGRES_USER=bingo
      - POSTGRES_PASSWORD=bingo

  redis:
    container_name: bingo-redis
    image: redis:alpine
    volumes:
      - redis:/data

  app:
    container_name: bingo-app
    image: bingo:latest
    depends_on:
      - db
      - redis
    volumes:
      - ./config/bingo.example.yml:/bingo/bingo.yml
    ports:
      - "8080:80"

volumes:
  db:
  redis:
