log_level: debug

appearance:
  title: "Bingo"
  theme: "dark"
  #icon: /path/to/icon.svg

db:
  driver: postgres
  host: db
  port: 5432
  database: bingo
  username: bingo
  password: bingo
  ssl: disable

redis:
  host: redis
  port: 1111
  password: 1111

extensions:
  visibility:
    enabled: true

  expiry:
    enabled: true
    durations:
      - 0
      - 5
      - 60
      - 1440

  highlight:
    enabled: true
    languages: base #base/all/custom
    custom_languages:
      - "Go"
      - "Python3"
      - "HTML"
