log_level: debug

appearance:
  title: "Bingo"
  theme: "dark"

db:
  driver: postgres
  host: db
  port: 5432
  database: bingo
  username: bingo
  password: bingo
  ssl: disable

extensions:
  visibility:
    enabled: true

  highlight:
    enabled: true

  expiry:
    enabled: true
