log_level: info

theme:
  default: light
  title: Pastebin

db:
  driver: postgres
  host: db
  port: 5432
  database: bingo
  username: bingo
  password: bingo
  ssl: disable

auth:
  enabled: false
  default_mode: standard
  default_role: editor
  registration: true
  session_name: session_bingo
  secure_cookie: false

expiry:
  enabled: true

highlight:
  enabled: true

visibility:
  enabled: true
  default: listed
