log_level: debug

theme:
  default: light
  title: Pastebin

db:
  driver: postgres
  host: db
  port: 5432
  database: bingo
  username: bingo
  password: bingo
  ssl: disable

auth:
  enabled: true
  default_mode: standard
  default_role: editor
  session:
    name: session_bingo
    secure_cookie: false
    store: redis
    redis:
      host: redis
      port: 6379
      password: ""
      database: 0
  standard:
    enabled: true
    allow_registration: true
  ldap:
    enabled: true
    host: "localhost"
    port: 389
    tls: true
    base: "ou=users,dc=example,dc=com"
    bind:
      dn: ""
      password: ""
    attributes:
      uid: "uid"
      name: "givenName"
      email: "mail"
    filter:
      user: "(objectClass=posixAccount)"
      admin: "(memberOf=cn=admin-group,ou=example,dc=example,dc=org)"
      editor: "(memberOf=cn=admin-group,ou=example,dc=example,dc=org)"
      viewer: "(memberOf=cn=admin-group,ou=example,dc=example,dc=org)"

expiry:
  enabled: true

highlight:
  enabled: true

visibility:
  enabled: true
  default: listed
