log_level: debug

theme:
  default: light
  title: Pastebin

db:
  driver: postgres
  host: db
  port: 5432
  database: bingo
  username: bingo
  password: bingo
  ssl: disable

auth:
  enabled: true
  default_mode: standard
  default_role: editor
  registration: true
  session:
    name: session_bingo
    secure_cookie: false
    store:
      type: redis
      host: redis
      port: 6379
      password: ""
      database: 0

expiry:
  enabled: true

highlight:
  enabled: true

visibility:
  enabled: true
  default: listed
