log_level: trace

appearance:
  title: "Pastebin"
  theme: "light"

db:
  driver: postgres
  host: db
  port: 5432
  database: bingo
  username: bingo
  password: bingo
  ssl: disable

auth:
  type: standard
  disable_registration: true
  session:
    name: session_bingo
    timeout: 180
    idle_timout: 20
    secure_cookie: true

extensions:
  expiry:
    enabled: true

  highlight:
    enabled: true

  visibility:
    enabled: true
